### ISSUE TITLE
Online book not updating

### ISSUE THREAD

**Issue by gibernas** [duckietown/docs-duckumentation#12]
It looks like the online Duckiebook 

http://docs.duckietown.org/DT18/duckumentation/out/documentation_style_guide.html)
is not updating from the files in github:

https://github.com/duckietown/docs-duckumentation/edit/master/book/duckumentation/30_style_guide/76_style_guide.md

as if I compile locally `laptop-container` is not showing the icons anymore. Plus on the online Duckiebook a whole piece of section (the one talking about watchtower/traffic light is missing (you can see it by trying to edit on github

**Comment by liampaull** [comment]
I believe this is fixed
