### ISSUE TITLE
Consolidate Duckumentation READMEs

### ISSUE THREAD

**Issue by breandan** [duckietown/docs-duckumentation#6]
The Duckumentation READMEs are duplicated across all `docs-*` repositories. It would be helpful to have a single authoritative readme.

**Comment by tanij** [comment]
The current readme is self-referential (link send to the same page), but one can't find the actual instructions.

**Comment by liampaull** [comment]
@tanij I don't understand what you mean

**Comment by sunsibar** [comment]
@liampaull  The link on the readme [here](https://github.com/duckietown/docs-duckumentation) links to the [same page](https://github.com/duckietown/docs-duckumentation), so it's a dead end for people looking for how to compile the book

**Comment by liampaull** [comment]
ok I updated the README to be more useful
